### ISSUE TITLE
Permanently giving full speed

### ISSUE THREAD

**Issue by WickedFreaK** [Zilox135/A20Modlets#13]
When entering the plane, and immediately pushing handbrake and or backwards key I'm able to hold it in place.
As soon as i release the keys it starts moving full speed.
When in motion, cant be stopped by any keys until it gets stopped by an object.

**Comment by WickedFreaK** [comment]
I just saw you had the problem before. Too bad it seems some update apparently brought it back :(

**Comment by Zilox135** [comment]
Can you try updating the mod. I have fixed this issue some time ago, and let me know if the issue is resolved?

**Comment by WickedFreaK** [comment]
Apologies. It seems I was to dumb to update it right. Yes it it not happening anymore.
Thanx for the mod and your fast answer.
