### ISSUE TITLE
download

### ISSUE THREAD

**Issue by emperoverlord** [Zilox135/A20Modlets#14]
i have tried to download the AH-64 modlet and it does not appear in game, is this for 20.1 or is there a different way to download this

**Comment by Zilox135** [comment]
> i have tried to download the AH-64 modlet and it does not appear in game, is this for 20.1 or is there a different way to download this

It will work for any version of A20. you need to download it unzip the file, make sure there isn't a another folder inside that one. And then put AH-64 mod folder inside your Mods folder of 7 days to die

**Comment by emperoverlord** [comment]
thats what i was missing thank you
