### ISSUE TITLE
Dyeing the Jeep

### ISSUE THREAD

**Issue by michaelarlt** [Zilox135/A20Modlets#2]
For me its not possible to dye the gladiator for some reason. Is there any specific way?

**Comment by Zilox135** [comment]
> For me its not possible to dye the gladiator for some reason. Is there any specific way?

Are you putting the dyes into the dye slot next to where the vehicle mods go?

**Comment by michaelarlt** [comment]
yes, even if i try shift+click it isnt working. Also the dye does'nt blink as if it is not compatible with the vehicle somehow

**Comment by Zilox135** [comment]
> well i tried, even if i try shift+click it isnt working. Also the dye does'nt blink as if it is not compatible with the vehicle somehow

Do you have any other mods installed except this one? I have tested it again and it works. https://youtu.be/rhUnTQtqT9g

**Comment by michaelarlt** [comment]
Issue is related to the PaintJob modlet created by Éric Beaudon. It is probably preventing the dyeing of vehicles in general, not just for his custom vehicles
