### ISSUE TITLE
JeepGladiator mod not working for my dedicated server A20

### ISSUE THREAD

**Issue by ReneeNiv** [Zilox135/A20Modlets#3]
Hi there- i cant get the picture files to show up in game (atlas) and also not the jeep once its being build.
It all shows blank blocks with numbers on my inventory - i will include the error i get when i try to spawn it in world after being build. https://gyazo.com/ff8fb36f00e0358ba67c2c5d2fa3edd1

Please help as i am really stuck and dont know how to proceed from here 

Thanks

**Comment by Zilox135** [comment]
> Hi there- i cant get the picture files to show up in game (atlas) and also not the jeep once its being build. It all shows blank blocks with numbers on my inventory - i will include the error i get when i try to spawn it in world after being build. https://gyazo.com/ff8fb36f00e0358ba67c2c5d2fa3edd1
> 
> Please help as i am really stuck and dont know how to proceed from here
> 
> Thanks

Hello. The mod must be installed in your single player game as well as the server.

**Comment by ReneeNiv** [comment]
Hi there thanks for your fast response - it is installed on both the server and client pc's

**Comment by Zilox135** [comment]
> Hi there thanks for your fast response - it is installed on both the server and client pc's

Can you try if it works in single player, if it does then it's not installed correctly on the server, or the other way around.

**Comment by ReneeNiv** [comment]
Let me do that and see if it works -

**Comment by ReneeNiv** [comment]
ok its working on single player -Do you know where i went wrong on installing it on the server ?

**Comment by ReneeNiv** [comment]
I am currently starting a new map, so its a fresh map and start - i would like to get it fixed before i start the game up for the first time.

**Comment by ReneeNiv** [comment]
Its working now on the new map /game- thanks for your support and help

**Comment by Zilox135** [comment]
Problem has been resolved.
