### ISSUE TITLE
Advanced Forge and SMX

### ISSUE THREAD

**Issue by jameswlane** [Zilox135/A20Modlets#4]
Love Advanced Forge its one of my top five favorite mods. I also use the SMX, Sirillion finally released a SMX UI for a20. It looks like SMX UI and Advanced Forge is not playing well. I would love to use both, so I figured I would add a issue. I understand that this would require updating the mod to play friendly with another mod. If this is something you wouldn't want to deal with I totally understand. With SMX having over half a million downloads and over a million page views on Nexus Mods, maybe its something you want to tackle. I am sure I am not the only one who uses this mod that will run into this issue. I hope you have a great weekend. 

Default Vanilla Forge
![Screenshot 2022-01-14 184919](https://user-images.githubusercontent.com/794161/149602583-a5a0db4f-d857-419a-81a5-53ac86dfc7ca.jpg)

Advanced Forge
![Screenshot 2022-01-14 184845](https://user-images.githubusercontent.com/794161/149602202-aff90edd-0701-4bdc-b535-09a8edd9ff12.jpg)

**Comment by Zilox135** [comment]
> Love Advanced Forge its one of my top five favorite mods. I also use the SMX, Sirillion finally released a SMX UI for a20. It looks like SMX UI and Advanced Forge is not playing well. I would love to use both, so I figured I would add a issue. I understand that this would require updating the mod to play friendly with another mod. If this is something you wouldn't want to deal with I totally understand. With SMX having over half a million downloads and over a million page views on Nexus Mods, maybe its something you want to tackle. I am sure I am not the only one who uses this mod that will run into this issue. I hope you have a great weekend.
> 
> Default Vanilla Forge ![Screenshot 2022-01-14 184919](https://user-images.githubusercontent.com/794161/149602583-a5a0db4f-d857-419a-81a5-53ac86dfc7ca.jpg)
> 
> Advanced Forge ![Screenshot 2022-01-14 184845](https://user-images.githubusercontent.com/794161/149602202-aff90edd-0701-4bdc-b535-09a8edd9ff12.jpg)

Hi. I have released update V2.7 for the Advanced Forge which includes some new features and an SMX UI compatibility patch.

**Comment by Replicatorz** [comment]
I am getting the same issue and the compatibility patch didn't seem to work either unfortunately.

"2022-01-17T08:03:32 69.508 WRN XML patch for "XUi/xui.xml" from mod "Advanced Forge SMX UI Patch" did not apply: 2022-01-17T08:03:32 69.508 WRN XML patch for "XUi/xui.xml" from mod "Advanced Forge SMX UI Patch" did not apply: 2022-01-17T08:03:32 69.508 WRN XML patch for "XUi/xui.xml" from mod "Advanced Forge SMX UI Patch" did not apply: 2022-01-17T08:03:32 69.508 WRN XML patch for "XUi/xui.xml" from mod "Advanced Forge SMX UI Patch" did not apply: 2022-01-17T08:03:32 69.906 INF Loaded (local): XUi/xui"

This is the error i got.

**Comment by Zilox135** [comment]
> I am getting the same issue and the compatibility patch didn't seem to work either unfortunately.
> 
> "2022-01-17T08:03:32 69.508 WRN XML patch for "XUi/xui.xml" from mod "Advanced Forge SMX UI Patch" did not apply: 2022-01-17T08:03:32 69.508 WRN XML patch for "XUi/xui.xml" from mod "Advanced Forge SMX UI Patch" did not apply: 2022-01-17T08:03:32 69.508 WRN XML patch for "XUi/xui.xml" from mod "Advanced Forge SMX UI Patch" did not apply: 2022-01-17T08:03:32 69.508 WRN XML patch for "XUi/xui.xml" from mod "Advanced Forge SMX UI Patch" did not apply: 2022-01-17T08:03:32 69.906 INF Loaded (local): XUi/xui"
> 
> This is the error i got.

Can you send a picture of all the mods in your folder?

**Comment by Replicatorz** [comment]
![aforge](https://user-images.githubusercontent.com/44933932/149801980-c190310f-59f7-418d-af50-d81a716036ba.jpg)

**Comment by Zilox135** [comment]
> ![aforge](https://user-images.githubusercontent.com/44933932/149801980-c190310f-59f7-418d-af50-d81a716036ba.jpg) It should only need to be on server if clients have advanced forge and smx mods installed right?

Thanks for that. I've found the problem and fixed it. Here is a link to the mod again, it will be uploaded to the main site in a little while https://downgit.github.io/#/home?url=https://github.com/Zilox135/A20Modlets/tree/main/0-Advanced%20ForgeV2.7

**Comment by Zilox135** [comment]
This has been fixed.

**Comment by jameswlane** [comment]
@Zilox135  you are awesome, thank you
