### ISSUE TITLE
Add voltage requirements to advanced forge?

### ISSUE THREAD

**Issue by Evilmirth** [Zilox135/A20Modlets#5]
I'd love to add the advanced forge to my multiply player server, but don't want to let my players smelt thing for free.  Is there a way you could add a voltage requirement to it?

**Comment by Zilox135** [comment]
> I'd love to add the advanced forge to my multiply player server, but don't want to let my players smelt thing for free. Is there a way you could add a voltage requirement to it?

Unfortunately there isn't an easy way for me to add a voltage requirement for smelting. It would require a good bit of coding work, I can consider it for the future but at the moment I don't have the time to do something like that.

**Comment by Replicatorz** [comment]
This mod should atleast use electricity even if high consumption as i would assume something like this would be, like 30 watts per advanced forge.

**Comment by Zilox135** [comment]
> This mod should atleast use electricity even if high consumption as i would assume something like this would be, like 30 watts per advanced forge.

Also not easily doable, but I understand where you are coming from.
