### ISSUE TITLE
Doesn't smelt when looking in the forges.

### ISSUE THREAD

**Issue by Replicatorz** [Zilox135/A20Modlets#6]
It smelts, but it's like it's paused when looking in the forge, then getting out and going back in again shows it did something but paused again.

**Comment by Zilox135** [comment]
> It smelts, but it's like it's paused when looking in the forge, then getting out and going back in again shows it did something but paused again.

I am aware of this issue, but there isn't a way for me to fix it, although it does work just fine so I don't think it's that big of a deal.
