### ISSUE TITLE
Advanced Forge no output area

### ISSUE THREAD

**Issue by imtherealchaka** [Zilox135/A20Modlets#7]
I have recently started a A20 run and added in Advanced forge partway into a playthrough and unfortunately there aren't any output slots for the Advanced Forge. 
![Screenshot_1](https://user-images.githubusercontent.com/98003043/150060222-294c2abd-0c7b-4b42-9bac-5be5a08920b2.png)
![Screenshot_2](https://user-images.githubusercontent.com/98003043/150060299-f7cf0bb9-2618-453f-ba9b-800f3a9ee9b0.png)

**Comment by Zilox135** [comment]
> I have recently started a A20 run and added in Advanced forge partway into a playthrough and unfortunately there aren't any output slots for the Advanced Forge. ![Screenshot_1](https://user-images.githubusercontent.com/98003043/150060222-294c2abd-0c7b-4b42-9bac-5be5a08920b2.png) ![Screenshot_2](https://user-images.githubusercontent.com/98003043/150060299-f7cf0bb9-2618-453f-ba9b-800f3a9ee9b0.png)

Hello. thanks for reporting this issue. It was an issue with the SMX UI mod itself, I have fixed it and notified sirillion of the problem. Please download the patch again.

**Comment by Zilox135** [comment]
This issue has been fixed.
