### ISSUE TITLE
Gyrocopter doesn't work

### ISSUE THREAD

**Issue by Kartstig** [Zilox135/A20Modlets#9]
Version A20

Other players cannot interact with the Gyrocopter :disappointed:

**Comment by Zilox135** [comment]
Not an issue.

**Comment by Kartstig** [comment]
I see you listed that mod as a requirement. Do you have any links to it? I'm having trouble finding it

**Comment by Zilox135** [comment]
> I see you listed that mod as a requirement. Do you have any links to it? I'm having trouble finding it

I'm talking about the expanded vehicle seating that install onto your vehicle in the game.

**Comment by Kartstig** [comment]
Yup all is working properly. Thank you
